LearnEnglishVirtually/LearnEnglishVirtually/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CourseManagement.urls')),
    path('',include('TestManagement.urls')),
    path('',include('authentication.urls')),

]

LearnEnglishVirtually/Test/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('testListView/', TestManagementListView.as_view(), name='main-view'),
    path('testListView/<pk>/', test_management_view, name='quiz-view'),
    path('testListView/<pk>/save/', save_test_management_view, name='save-view'),
    path('testListView/<pk>/data/', test_data_details_view, name='quiz-data-view'),
     path('try/',tryFun,name='tryFun'),
]

LearnEnglishVirtually/authentication/urls.py
from django.urls import path
from .views import loginFunction,registerFunction,verifyUser,changePassword,logoutFun,updateUserProfile
from django.contrib.auth import views as auth_views

# app_name = 'authentication'
urlpatterns = [
    path('login/',loginFunction,name="login"),
    path('reg/',registerFunction,name="reg"),
    path('verify/',verifyUser,name="verify"),
    path('logout/',logoutFun,name="logout"),
    # path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='html/reset_password_form.html'),name='password_reset'), #submit email form
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='html/password_reset_done.html'),name='password_reset_done'), # email sent success message for user
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='html/password_reset_complete.html'),name='password_reset_confirm'), # link is sent to email to reset password
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='html/password_reset_complete_done.html'),name='password_reset_complete'), #password successfully changed message
    path('changePassword/',changePassword,name="changePassword"),
    path('updateUserProfile/',updateUserProfile,name="updateUserProfile"),
]

LearnEnglishVirtually/authentication/models.py
from django.db import models

# Create your models here.
class PreRegistration(models.Model):
    username = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password1    = models.CharField(max_length=100)
    password2 = models.CharField(max_length=100)
    otp = models.CharField(max_length=10)

    def __str__(self):
        return self.first_name+" "+self.last_name
    

LearnEnglishVirtually/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from django.utils.translation import  gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm,PasswordChangeForm,PasswordResetForm, UsernameField, UserChangeForm
from django.core import validators

def validate_username(value):
    if len(value)<=2:
        raise forms.ValidationError(f"Your username cannot be of {len(value)}  letters")

def validate_email(value):
    email = User.objects.filter(email=value)
    if email:
        raise forms.ValidationError(f"This '{value}' email already exists!!!!!!! ")


class UserCreation(UserCreationForm):
    password1 = forms.CharField(label="Password", widget = forms.PasswordInput(attrs={"placeholder":"Password",'autocomplete':'new-password','id':''}),error_messages={"required":"Please enter password"},)
    password2 = forms.CharField(label="Repeat your password",widget= forms.PasswordInput(attrs={"placeholder":"Repeat your password",'autocomplete':'new-password','id':''}),help_text="Make sure your password contains 'small letter','capital letter','numbers' and 'symbols'",error_messages={"required":"Re-Enter password field cannot be empty"})
    username = forms.CharField(label="username",widget=forms.TextInput(attrs={"placeholder":"Username","id":"username",'class':'','id':'name'}),validators=[validate_username])
    first_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"First Name","required":True,'id':'fname'}),error_messages={"required":"First name cannot be empty"})
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Last Name","required":True,'id':'lname'}),error_messages={"required":"Last name cannot be empty"})
    email = forms.CharField(widget=forms.EmailInput(attrs={"required":True,"Placeholder":"Email",'autocomplete':'username','id':'email'}),validators=[validate_email])
    class  Meta:
        model = User
        fields =['username','email','first_name','last_name','password1','password2']
        

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"placeholder":"Username",'class':'','id':'your_name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"password",'autocomplete':'current-password','class':'','id':'your_pass'}))    


class VerifyForm(forms.Form):
    otp = forms.CharField(label='OTP',max_length=70,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'One Time Password','required':True}),error_messages={'required':'One Time Password is Required'})

class ChangePasswordUserForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'','placeholder':'old password'}),error_messages={"required":"Old Password Field is required"})
    new_password1 =forms.CharField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'','placeholder':'new password'}),error_messages={"required":"New Password Field is  required"}) 
    new_password2 =forms.CharField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'','placeholder':'confirm password'}),error_messages={"required":"Confirm Field is  required"}) 
    

class UserUpdateForm(UserChangeForm):
    password = None
    email = forms.CharField(widget=forms.EmailInput(attrs={"required":True,"Placeholder":"Email",'autocomplete':'username','id':'email','disabled':True}),validators=[validate_email])
    first_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"First Name","required":True,'id':'fname'}),error_messages={"required":"First name cannot be empty"})
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Last Name","required":True,'id':'lname'}),error_messages={"required":"Last name cannot be empty"})
    
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','last_login','date_joined']

LearnEnglishVirtually/authentication/views.py
from django.contrib.auth import authenticate, forms, login, logout
from django.shortcuts import render
from .forms import UserCreation,LoginForm,VerifyForm,ChangePasswordUserForm,UserUpdateForm
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
import random
from django.contrib.auth.models import User
from .models import PreRegistration

# Create your views here.
def creatingOTP():
    otp = ""
    for i in range(5):
        otp+= f'{random.randint(0,9)}'
    return otp

def sendEmail(email,fname):
    otp = creatingOTP()
    print("Successfully done!!!!!!!!")
    email_message = f"""
Dear Sir/Madam,
{fname}
ATTN : Please do not reply to this email.This mailbox is not monitored and you will not receive a response.
Your One Time Password (OTP ) is {otp}.
If you have any queries, Please contact us at,
learn English Virtually,
Thali,Kathmandu, Nepal.
Phone # 977-9803955983
Email Id: learnenglishvirtually2078@gmail.com
Warm Regards,
Learn English Virtually."""
    send_mail(
    'One Time Password',
    email_message,
    settings.EMAIL_HOST_USER,
    [email],
    fail_silently=False,
    )
    return otp

def registerFunction(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreation(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                fname = form.cleaned_data['first_name']
                otp = sendEmail(email,fname)
                dt = PreRegistration(first_name=form.cleaned_data['first_name'],last_name=form.cleaned_data['last_name'],username= form.cleaned_data['username'],email=email,otp=otp,password1 = form.cleaned_data['password1'],password2 = form.cleaned_data['password2'])
                dt.save()
                return HttpResponseRedirect('/verify/')
                # form.save()
                # messages.success(request, 'Account is created Successfully!')
        else:
            form = UserCreation()
        return render(request,'html/register.html',{'form':form})
    else:
        return HttpResponseRedirect('/')


def loginFunction(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request = request,data = request.POST)
            # username = request.POST['username']
            # if '@gmail.com' in username:
            #         print(User.objects.all())
            #         get_user_obj = User.objects.get(email = username)
            #         username = get_user_obj.username
            # pas = request.POST['password']
            # usr = authenticate(username= username,password=pas)
            # login(request,usr)
            # return HttpResponseRedirect('/home/')
            if form.is_valid():
                print("Worked")
                username = form.cleaned_data['username']
                pas = form.cleaned_data['password']
                usr = authenticate(username= username,password=pas)
                login(request,usr)
                return HttpResponseRedirect('/')
        else:
            form = LoginForm()
        return render(request,'html/login.html',{'form':form})
    else:
        return HttpResponseRedirect('/')

def verifyUser(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = VerifyForm(request.POST)
            if form.is_valid():
                otp = form.cleaned_data['otp']
                data = PreRegistration.objects.filter(otp = otp)
                if data:
                    username = ''
                    first_name = ''
                    last_name = ''
                    email = ''
                    password1 = ''
                    for i in data:
                        print(i.username)
                        username = i.username
                        first_name = i.first_name
                        last_name = i.last_name
                        email = i.email
                        password1 = i.password1

                    user = User.objects.create_user(username, email, password1)
                    user.first_name = first_name
                    user.last_name = last_name
                    user.save()
                    data.delete()
                    messages.success(request,'Account is created successfully!')
                    return HttpResponseRedirect('/verify/')   
                else:
                    messages.success(request,'One Time Password is wrong')
                    return HttpResponseRedirect('/verify/')
        else:            
            form = VerifyForm()
        return render(request,'html/verify.html',{'form':form})
    else:
        return HttpResponseRedirect('/success/')


def logoutFun(request):
    logout(request)
    return HttpResponseRedirect('/login/')


def changePassword(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            changePasswordForm = ChangePasswordUserForm(user=request.user,data= request.POST)
            if changePasswordForm.is_valid():
                changePasswordForm.save()
                messages.success(request,"Your password is changed successfully,")
                return HttpResponseRedirect('/login/')
                
        else:
            changePasswordForm = ChangePasswordUserForm(user=request.user)
        return render(request,'html/changePassword.html',{'form':changePasswordForm})
    else:
        return HttpResponseRedirect('/login/')

def updateUserProfile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = UserUpdateForm(request.POST,instance= request.user)
            uname = request.POST['username']
            fname = request.POST['first_name']
            lname = request.POST['last_name']
            # checkUname = User.objects.filter(username=uname)
            # if(checkUname):
            #     if(checkUname.email == request.user.email ):
            #         print("success")
            User.objects.filter(email=request.user.email).update(username=uname,first_name=fname,last_name=lname)
            messages.success(request,"Your profile is updated successfully")
            if form.is_valid():
                User.objects.filter(username=request.user.username).update(username="sumanraj")
                form.save()
                messages.success(request,"Your profile is updated successfully")
                return HttpResponseRedirect('/updateUserProfile/')
        else:        
            form = UserUpdateForm(instance= request.user)
        return render(request,'html/updateProfile.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')

LearnEnglishVirtually/authentication/templates/html/PlaceholderFieldPass_res_com.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function(){
        $("#id_new_password1").attr("placeholder", "Enter New Password");
        $("#id_new_password2").attr("placeholder", "Enter Comfirm Password");

      });
</script>

LearnEnglishVirtually/authentication/templates/html/changePassword.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">{% endblock css %}
{% block content %}
 <section class="signup">
            <div class="container2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h3 class="form-title">Change Password</h3>
                        <form method="POST" class="register-form" id="register-form" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            {{form.old_password}}
                            <small class="text-danger">{{form.old_password.errors|striptags}}</small>
                           
                        </div>
                            
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                {{form.new_password1}}
                                <small class="text-danger">{{form.new_password1.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                {{form.new_password2}}
                                <small class="text-danger">{{form.new_password2.errors|striptags}}</small>
                               
                            </div>
                           
                            <div class="text-danger mt-3">
           {% for error in  form.non_field_errors  %}
         {{error}}
  {% endfor %}
           </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Change Password"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'auth/images/changePassword.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'main' %}" class="signup-image-link">Cancel</a>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}

LearnEnglishVirtually/authentication/templates/html/login.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">
{% endblock css %}

{% block content %}
<section class="sign-in">
    <div class="container2">
        <div class="signin-content">
            <div class="signin-image">
                <figure><img src="{% static 'auth/images/signin-image.jpg' %}" alt="sing up image"></figure>
                <a href="{% url 'reg' %}" class="signup-image-link text-primary underline" ><u> Create an account</u></a>
            </div>

            <div class="signin-form">
                <h2 class="form-title">Sign In</h2>
                <form method="POST" class="register-form" id="login-form" novalidate>
                {% csrf_token %}
                    <div class="form-group">
                        <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.username}}
                        <small class="text-danger font-italic">{{form.username.errors|striptags}}</small>
                        
                       
                    </div>
                    <div class="form-group">
                        <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                        
                         {{form.password}}
                         <small class="text-danger font-italic">{{form.password.errors|striptags}}</small>
                         
                    </div>
                    <small class="text-danger font-italic">{% for error in  form.non_field_errors  %}
                    {{error}}
                    {% endfor %}</small>
                    
                    <div class="form-group">
                        {% comment %} <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" /> {% endcomment %}
                        <label for="remember-me" class="label-agree-term"><span><span></span></span><a href="{% url 'password_reset' %}" class="text-primary">Forget Password?</a></label>
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

LearnEnglishVirtually/authentication/templates/html/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">{% endblock css %}
{% block content %}
 <section class="signup">
            <div class="container2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h3 class="form-title">Forget Password</h3>
                        <form method="POST" class="register-form" id="register-form" novalidate>
                        {% csrf_token %}
                        
                            
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                {{form.new_password1}}
                                <small class="text-danger">{{form.new_password1.errors|striptags}}</small>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                {{form.new_password2}}
                                <small class="text-danger">{{form.new_password2.errors|striptags}}</small>
                               
                            </div>
                           
                            <div class="text-danger mt-3">
           {% for error in  form.non_field_errors  %}
         {{error}}
  {% endfor %}
           </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Change Password"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'auth/images/forgetPassword.png' %}" alt="sing up image"></figure>
                     
                    </div>
                </div>
            </div>
        </section>
        {% include 'html/PlaceholderFieldPass_res_com.html' %}
{% endblock content %}





{% comment %} {% extends 'base.html' %}
{% block content %}
<form action="" method="post" novalidate>
{% csrf_token %}
{{form.new_password1}}
{{form.new_password1.errors}}
{{form.new_password2}}
{{form.new_password2.errors}}
<input type="submit" value="Change">
</form>
{% endblock content %} {% endcomment %}

LearnEnglishVirtually/authentication/templates/html/password_reset_complete_done.html
    {% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">{% endblock css %}
{% block content %}
 <section class="signup">
            <div class="container2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h4 class="form-title">Password Reset Complete</h4>
                        <p >
                            Your password has been set. You may go ahead and log in now.                            
                            </p>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'auth/images/completed.png' %}" alt="sing up image"></figure>
                        <a href="{% url 'login' %}" class="text-primary"><b><u>Login</u></b></a> 
                    </div>
                </div>
            </div>
        </section>
  
{% endblock content %}

LearnEnglishVirtually/authentication/templates/html/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">{% endblock css %}
{% block content %}
 <section class="signup">
            <div class="container2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h4 class="form-title">Password Reset Sent</h4>
                        <p>
                            We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                            
                            If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
                            </p>

                            
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'auth/images/sent.jpg' %}" alt="sent image"></figure>
                        
                    </div>
                </div>
            </div>
        </section>
  
{% endblock content %}

LearnEnglishVirtually/authentication/templates/html/placeholderForResetPassword.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function(){
        $("#id_email").attr("placeholder", "Enter Your Email Address");

      });
</script>

LearnEnglishVirtually/authentication/templates/html/register.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">
{% endblock css %}

{% block content %}
<section class="signup">
    <div class="container2">
        <div class="signup-content">
            <div class="signup-form">
                <h2 class="form-title">Sign up</h2>
                <form method="POST" class="register-form" id="register-form" novalidate>
                {% csrf_token %}
                    <div class="form-group">
                        <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.username}}
                        <small class="text-danger">{{form.username.errors|striptags}}</small>
                        
                    </div>

                    <div class="form-group">
                        <label for="fname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.first_name}}
                        <small class="text-danger">{{form.first_name.errors|striptags}}</small>
                        
                    </div>

                    <div class="form-group">
                        <label for="lname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.last_name}}
                        <small class="text-danger">{{form.last_name.errors|striptags}}</small>
                        
                    </div>

                    <div class="form-group">
                        <label for="email"><i class="zmdi zmdi-email"></i></label>
                        {{form.email}}
                        <small class="text-danger">{{form.email.errors|striptags}}</small>
                    </div>
                    <div class="form-group">
                        <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                        {{form.password1}}
                        <small class="text-danger">{{form.password1.errors|striptags}}</small>
                    </div>
                    <div class="form-group">
                        <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                        {{form.password2}}
                        <small class="text-danger">{{form.password2.errors|striptags}}</small>
                       
                    </div>
                    
                    <div class="text-danger mt-3">
   {% for error in  form.non_field_errors  %}
 {{error}}
    {% endfor %}
   </div>
                    <div class="form-group form-button">
                        <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                    </div>
                </form>
            </div>
            <div class="signup-image">
                <figure><img src="{% static 'auth/images/signup-image.jpg' %}" alt="sing up image"></figure>
                <a href="{% url 'login' %}" class="signup-image-link text-dark"><u>I am already member</u></a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

LearnEnglishVirtually/authentication/templates/html/reset_password_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'auth/css/login.css' %}">{% endblock css %}
{% block content %}
 <section class="signup">
            <div class="container2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h4 class="form-title">Password Reset</h4>
                        <form method="POST" class="register-form" id="register-form" novalidate>
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-email"></i></label>
                                {{form.email}}
                                <small class="text-danger">{{form.email.errors|striptags}}</small>
                                
                            </div>
                            <div class="text-danger mt-3">
           {% for error in  form.non_field_errors  %}
         {{error}}
  {% endfor %}
           </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Reset Password"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'auth/images/resetEmail.jpg' %}" alt="sing up image"></figure>
                        <p> Password reset instructions will be sent to this email address.
                        </p>
                    </div>
                </div>
            </div>
        </section>
        {% include 'html/placeholderForResetPassword.html' %}
{% endblock content %}




{% comment %} {% extends 'base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/reset_pd.css' %}">{% endblock css %}
{% block content %}

<!---->
<div class="container2 mt-md-5">
 <div class="card card-outline-secondary ">
                        <div class="card-header">
                            <h3 class="mb-0">Password Reset</h3>
                        </div>
                        <div class="card-body">
                        <form method='POST' novalidate>
                        {% csrf_token %}
                        {{form.email}} 
                        {{form.email.errors}}
                        <br>
                        <span id="helpResetPasswordEmail" class="form-text small text-muted">
                                            Password reset instructions will be sent to this email address.
                                        </span><br>
                        <input type="submit" value="Send Email" class="btn btn-success ">
                        </form>
                        </div>
                    </div>
</div>
{% endblock content %} {% endcomment %}